on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.0-noble
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: gh-pages
          path: reports
          sparse-checkout: json

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: app

      - name: Setup
        working-directory: app
        run: npm install

      - name: Copy previous reports
        run: mkdir -p reports/json && cp -r reports/json app/reports

      - name: Run scanner
        working-directory: app
        run: xvfb-run npm start

      - name: Deploy results
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          publish_dir: ./app/reports
          github_token: ${{ secrets.GITHUB_TOKEN }}
